export const LAY_DANH_SACH_KHOA_HOC = "LAY_DANH_SACH_KHOA_HOC"
export const GET_COURSES_LIST_REQUEST = "GET_COURSES_LIST_REQUEST"
export const GET_COURSES_LIST_SUCCESS = "GET_COURSES_LIST_SUCCESS"
export const GET_COURSES_LIST_FAILED = "GET_COURSES_LIST_FAILED"